name: Markdown lint

on:
  schedule:
    - cron: '5 8 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: make markdown-lint
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-link-check-config.json
        use-quiet-mode: no
        use-verbose-mode: yes
